trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the 'main' branch

pool:
  name: 'Default'  # Using the latest Ubuntu image for the pipeline agent

variables:
  # Define Terraform version and directory where Terraform code resides
  terraformVersion: '1.10.0'
  terraformWorkingDirectory: '/home/azure/terraform/tech_task'  # Path to your Terraform files on the agent (modify accordingly)

  # Azure Service Connection (pre-configured in Azure DevOps)
  serviceConnection: 'TestTask'  # Update with the name of your service connection

stages:
  - stage: 'Terraform_Initialize'
    displayName: 'Initialize Terraform'
    jobs:
      - job: 'Terraform_Init'
        displayName: 'Install and Initialize Terraform'
        steps:
          # Checkout the code from the repository
          - checkout: self

          # Install Terraform
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(terraformVersion)

          # Initialize Terraform in the specified directory
          - task: Bash@3
            displayName: 'Terraform Init'
            inputs:
              targetType: 'inline'
              script: |
                echo "Initializing Terraform in $(terraformWorkingDirectory)"
                cd $(terraformWorkingDirectory)
                terraform init
